#jasypt加密的密匙
jasypt:
  encryptor:
    password: nqJ#ki6po8&jv@fES5^FR4s9^XcK4p4i
spring:
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 114.67.169.54  # Redis服务器地址
    port: 6379         # Redis服务器连接端口
    password: ENC(PWTzQzVzSo6YYJRTmFIS2Q==)   # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 30000
    timeout: 5000  # 连接超时时间（毫秒）
    #自定义配置
  redis2:
    database: 1   # Redis数据库索引（默认为0）

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.67.169.54:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT&rewriteBatchedStatements=true
    username: ENC(PWTzQzVzSo6YYJRTmFIS2Q==)
    password: ENC(cIbOeKRtqpYMBE4j5SAexg==)
    ###################以下为hikari增加的配置###########################
    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
